import { NewsItem, LegalBasis, JobVacancy, IjazahStatus } from '@/types/tracer';

export const INITIAL_STATS = {
  totalAlumni: 3520,
  bekerjaWirausahaPercent: 87.5,
  kuliahPercent: 12.5,
  mitraIndustri: 142,
  lokerAktif: 28,
  respondenTahunIni: 1840,
};

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'news-1',
    title: 'Pelantikan Pengurus BKK Baru: Siap Salurkan Ratusan Alumni ke Berbagai Sektor Industri',
    excerpt: 'SMK Sasmita Jaya 2 memperkuat sinergi Bursa Kerja Khusus bersama puluhan mitra strategis industri nasional di Jabodetabek.',
    content: `SMK Sasmita Jaya 2 Pamulang resmi mengukuhkan jajaran pengurus Bursa Kerja Khusus (BKK) untuk periode 2026-2028. Langkah ini menjadi tonggak percepatan penyaluran lulusan langsung ke dunia usaha dan dunia industri (DUDI).
    
    Kepala Sekolah SMK Sasmita Jaya 2 menegaskan bahwa target penyerapan lulusan tahun ini dipatok menembus angka 90% dalam kurun waktu 3 bulan setelah kelulusan. BKK kini dilengkapi sistem digital terpadu untuk memudahkan verifikasi portofolio alumni dan matchmaking kompetensi industri.`,
    category: 'BKK & Karir',
    date: '24 Sep 2026',
    readTime: '3 min read',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    author: 'Tim Humas BKK',
  },
  {
    id: 'news-2',
    title: 'Tracer Study: Mengapa Sekolah Sangat Membutuhkan Partisipasi Data Anda?',
    excerpt: 'Pengisian kuesioner pelacakan alumni bukan sekadar formalitas, namun menjadi kompas penyusunan kurikulum vokasi masa depan.',
    content: `Tracer Study adalah instrumen resmi Kementerian Pendidikan dan Kebudayaan serta instrumen internal yayasan untuk mengukur relevansi materi ajar di sekolah dengan dinamika teknologi terbaru di tempat kerja.
    
    Data yang terkumpul memberikan gambaran jelas: bidang keahlian mana yang paling banyak dicari, sertifikasi apa yang paling bernilai tinggi, serta soft skills apa yang perlu ditingkatkan di ruang kelas.`,
    category: 'Tracer Study',
    date: '20 Sep 2026',
    readTime: '4 min read',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    author: 'Koordinator Tracer',
  },
  {
    id: 'news-3',
    title: 'Yayasan Sasmita Jaya Resmikan Fasilitas Workshop Otomotif & Lab Jaringan Terpadu',
    excerpt: 'Investasi sarana prasarana modern guna menunjang standarisasi sertifikasi kompetensi BNSP siswa dan alumni.',
    content: `Dalam rangka mendukung pembelajaran berbasis Teaching Factory (Tefa), Yayasan Sasmita Jaya meresmikan fasilitas laboratorium mutakhir di kampus Pamulang. Fasilitas ini terbuka juga untuk program upskilling dan reskilling bagi para alumni SMK Sasmita Jaya 2.`,
    category: 'Fasilitas',
    date: '18 Sep 2026',
    readTime: '2 min read',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    author: 'Redaksi Sekolah',
  },
  {
    id: 'news-4',
    title: 'Kerjasama Strategis dengan 25 Perusahaan IT & Otomotif Diteken',
    excerpt: 'Peluang magang bersertifikat dan rekrutmen jalur prioritas bagi lulusan SMK Sasmita Jaya 2.',
    content: `Sebanyak 25 pimpinan korporasi menandatangani MoU keselarasan vokasi dengan SMK Sasmita Jaya 2. Melalui MoU ini, kurikulum industri akan langsung diselaraskan ke dalam silabus kejuruan TKJ, RPL, TBSM, dan TKRO.`,
    category: 'Kemitraan DUDI',
    date: '12 Sep 2026',
    readTime: '3 min read',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80',
    author: 'Tim Kerjasama Industri',
  },
  {
    id: 'news-5',
    title: 'Tips Memilih Jalur Karir: Kerja, Kuliah, atau Berwirausaha?',
    excerpt: 'Panduan praktis bagi alumni baru dalam memetakan potensi diri dan peluang masa depan yang berkelanjutan.',
    content: `Memasuki masa pasca-kelulusan SMK sering kali menghadirkan pilihan krusial. Artikel ini mengupas perbandingan fleksibilitas kuliah kelas karyawan, akselerasi karir korporat, hingga membangun usaha mandiri digital.`,
    category: 'Panduan Karir',
    date: '08 Sep 2026',
    readTime: '5 min read',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    author: 'Guru BK & Konselor',
  },
  {
    id: 'news-6',
    title: 'Pentingnya Sertifikasi BNSP bagi Daya Saing Lulusan di Era Industri 4.0',
    excerpt: 'Sertifikat kompetensi resmi menjadi pembeda utama saat bersaing di bursa tenaga kerja nasional dan regional.',
    content: `Lembaga Sertifikasi Profesi (LSP) SMK Sasmita Jaya 2 terus mendorong seluruh alumni untuk memanfaatkan fasilitas uji kompetensi berstandar BNSP guna memvalidasi kemampuan teknis di mata recruiter HRD.`,
    category: 'Sertifikasi',
    date: '01 Sep 2026',
    readTime: '4 min read',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    author: 'LSP SMK Sasmita Jaya',
  },
];

export const MOCK_LEGAL_BASES: LegalBasis[] = [
  {
    id: 'sk-1',
    number: 'Nomor 68 Tahun 2022',
    year: 'PERPRES 2022',
    title: 'Revitalisasi Pendidikan dan Pelatihan Vokasi',
    description: 'Menetapkan arah kebijakan dan strategi revitalisasi pendidikan vokasi dan pelatihan vokasi guna mewujudkan sumber daya manusia yang unggul dan berdaya saing.',
    badge: 'PERPRES 2022',
    pdfUrl: '/documents/Perpres-No-68-Tahun-2022.pdf',
  },
  {
    id: 'sk-2',
    number: 'Nomor 8 Tahun 2025',
    year: 'PERMENDIKDASMEN 2025',
    title: 'pemantauan kebekerjaan lulusan (tracer study)',
    description: 'Peraturan Menteri Pendidikan Dasar dan Menengah mengenai Petunjuk Teknis Pengelolaan Dana BOSP yang memuat pembiayaan pemantauan kebekerjaan lulusan (tracer study) SMK.',
    badge: 'PERMENDIKDASMEN 2025',
    pdfUrl: '/documents/Permendikdasmen-No-8-Tahun-2025.pdf',
  },
  {
    id: 'sk-3',
    number: 'Nomor 34 Tahun 2025',
    year: 'PERDIRJEN 2025',
    title: 'Pedoman Pelaksanaan Penelusuran Tamatan (Tracer Study) pada SMK',
    description: 'Peraturan Direktur Jenderal Pendidikan Vokasi, Pendidikan Khusus, dan Pendidikan Layanan Khusus tentang Pedoman Pelaksanaan Penelusuran Tamatan (Tracer Study) pada SMK.',
    badge: 'PERDIRJEN 2025',
    pdfUrl: '/documents/Perdirjen-Vokasi-No-34-Tahun-2025.pdf',
  },
  {
    id: 'sk-4',
    number: '3159/B/D2/DV.06.03/2026',
    year: 'SURAT EDARAN 2026',
    title: 'Pemberitahuan Pelaksanaan Penelusuran Tamatan SMK Tahun 2026',
    description: 'Surat resmi Direktorat SMK Kemendikdasmen perihal Pemberitahuan Pelaksanaan Penelusuran Tamatan SMK Tahun 2026 dan tata cara pengisian di aplikasi penelusuran tamatan SMK.',
    badge: 'SURAT EDARAN 2026',
    pdfUrl: '/documents/Surat-Edaran-Dirjen-No-3159-Tahun-2026.pdf',
  },
];

export const MOCK_JOBS: JobVacancy[] = [
  {
    id: 'job-1',
    title: 'Junior Network Administrator',
    company: 'PT Solusi Teknologi Nusantara',
    location: 'BSD City, Tangerang Selatan',
    type: 'Full-time',
    salary: 'Rp 5.200.000 - Rp 6.800.000',
    targetMajors: ['Teknik Komputer dan Jaringan', 'Rekayasa Perangkat Lunak'],
    postedAt: '25 Sep 2026',
    deadline: '15 Okt 2026',
    description: 'Bertanggung jawab atas instalasi, konfigurasi jaringan LAN/WAN, pemeliharaan router Mikrotik/Cisco, dan penanganan troubleshooting jaringan harian.',
    requirements: [
      'Lulusan SMK Sasmita Jaya 2 (TKJ / RPL)',
      'Memahami konfigurasi IP Address, Subnetting, Routing, & VLAN',
      'Memiliki sertifikat BNSP bidang Jaringan menjadi nilai tambah',
      'Mampu bekerja secara shift dan komunikatif',
    ],
    contactPerson: 'bkk-it@smksasmitajaya2.sch.id',
    isBkkPartner: true,
  },
  {
    id: 'job-2',
    title: 'Service Advisor & Teknisi Roda Dua',
    company: 'PT Astra Motor Sasmita Group',
    location: 'Pamulang, Tangerang Selatan',
    type: 'Full-time',
    salary: 'Rp 4.900.000 - Rp 5.800.000 + Insentif',
    targetMajors: ['Teknik Bisnis Sepeda Motor', 'Teknik Kendaraan Ringan Otomotif'],
    postedAt: '24 Sep 2026',
    deadline: '20 Okt 2026',
    description: 'Melakukan penerimaan servis pelanggan, diagnosa kerusakan mesin injeksi, tune up berkala, serta perbaikan komponen kelistrikan sepeda motor.',
    requirements: [
      'Lulusan TBSM atau TKRO',
      'Memiliki ketelitian tinggi dan kemampuan komunikasi pelanggan yang ramah',
      'Siap ditempatkan di cabang dealer resmi wilayah Tangsel / Jaksel',
    ],
    contactPerson: 'recruitment@astramotor-partner.id',
    isBkkPartner: true,
  },
  {
    id: 'job-3',
    title: 'Junior Frontend Web Developer',
    company: 'PT Kreasi Digital Sinergi',
    location: 'Bintaro, Tangerang Selatan (Hybrid)',
    type: 'Full-time',
    salary: 'Rp 5.500.000 - Rp 7.500.000',
    targetMajors: ['Rekayasa Perangkat Lunak', 'Teknik Komputer dan Jaringan'],
    postedAt: '22 Sep 2026',
    deadline: '10 Okt 2026',
    description: 'Mengembangkan antarmuka aplikasi web modern menggunakan React/Vue, Tailwind CSS, serta integrasi REST API backend.',
    requirements: [
      'Menguasai HTML, CSS, JavaScript/TypeScript & Git',
      'Familiar dengan Tailwind CSS & React framework',
      'Menyertakan link portofolio GitHub / project demo',
    ],
    contactPerson: 'hrd@kreasidigital.co.id',
    isBkkPartner: true,
  },
  {
    id: 'job-4',
    title: 'Staff Administrasi & Keuangan Junior',
    company: 'Yayasan Sasmita Jaya Holding',
    location: 'Pamulang Barat, Tangerang Selatan',
    type: 'Full-time',
    salary: 'Rp 4.800.000 - Rp 5.600.000',
    targetMajors: ['Akuntansi & Keuangan Lembaga', 'Otomatisasi & Tata Kelola Perkantoran'],
    postedAt: '20 Sep 2026',
    deadline: '30 Okt 2026',
    description: 'Mengelola pencatatan kas kecil, pengarsipan dokumen digital, rekonsiliasi bank, dan pembuatan laporan keuangan bulanan.',
    requirements: [
      'Lulusan SMK Jurusan AKL atau OTKP',
      'Mahir Microsoft Excel (VLOOKUP, PIVOT TABLE) & Zahir / Accurate',
      'Disiplin, teliti, dan berintegritas tinggi',
    ],
    contactPerson: 'bkk-keuangan@smksasmitajaya2.sch.id',
    isBkkPartner: true,
  },
  {
    id: 'job-5',
    title: 'Program Magang Digital Marketing & Content Creator',
    company: 'PT Media Niaga Nusantara',
    location: 'Ciputat, Tangerang Selatan',
    type: 'Internship / Magang',
    salary: 'Uang Saku Rp 2.500.000 / bln',
    targetMajors: ['Bisnis Daring & Pemasaran', 'Rekayasa Perangkat Lunak'],
    postedAt: '19 Sep 2026',
    deadline: '28 Okt 2026',
    description: 'Program magang intensif 6 bulan untuk mengelola konten media sosial TikTok/Instagram, livestreaming e-commerce, dan iklan digital.',
    requirements: [
      'Alumni SMK Sasmita Jaya 2 atau fresh graduate',
      'Kreatif, percaya diri di depan kamera, paham tren medsos',
      'Memiliki laptop sendiri',
    ],
    contactPerson: 'magang@medianiaga.id',
    isBkkPartner: true,
  }
];

export const MOCK_IJAZAH_DATABASE: Record<string, IjazahStatus> = {
  '0051234567': {
    nisn: '0051234567',
    nama: 'Ahmad Dani',
    jurusan: 'Teknik Komputer dan Jaringan',
    tahunLulus: 2024,
    statusPengambilan: 'SUDAH_DIAMBIL',
    nomorIjazah: 'M-SMK/K13-3/24/0048291',
    nomorSertifikatBnsp: 'BNSP-TKJ-2024-99812',
    tanggalSiap: '15 Juli 2024',
    tanggalDiambil: '22 Juli 2024',
    lokasiPengambilan: 'Ruang Tata Usaha (TU) SMK Sasmita Jaya 2 Pamulang',
    persyaratan: [
      'Bebas Pustaka Perpustakaan (Lengkap)',
      'Bebas Administrasi Keuangan (Lengkap)',
      'Sidik Jari 3 Jari Tengah (Sudah)',
      'Formulir Tracer Study (Sudah Mengisi)',
    ],
    barcode: 'IJZ-SMK-SASMITA-2024-0048291',
  },
  '0067891234': {
    nisn: '0067891234',
    nama: 'Siti Nurhaliza',
    jurusan: 'Rekayasa Perangkat Lunak',
    tahunLulus: 2024,
    statusPengambilan: 'SIAP_DIAMBIL',
    nomorIjazah: 'M-SMK/K13-3/24/0048292',
    nomorSertifikatBnsp: 'BNSP-RPL-2024-55410',
    tanggalSiap: '15 Juli 2024',
    lokasiPengambilan: 'Loket 2 Pelayanan Alumni & Ijazah SMK Sasmita Jaya 2',
    persyaratan: [
      'Bebas Pustaka Perpustakaan (Lengkap)',
      'Bebas Administrasi Keuangan (Lengkap)',
      'Sidik Jari 3 Jari Tengah (Belum - Datang Langsung)',
      'Wajib menunjukkan Bukti Pengisian Tracer Study',
    ],
    barcode: 'IJZ-SMK-SASMITA-2024-0048292',
  },
  '0071239999': {
    nisn: '0071239999',
    nama: 'Rizky Pratama',
    jurusan: 'Teknik Bisnis Sepeda Motor',
    tahunLulus: 2024,
    statusPengambilan: 'PROSES_LEGALISIR',
    nomorIjazah: 'M-SMK/K13-3/24/0048293',
    nomorSertifikatBnsp: 'BNSP-TBSM-2024-11203',
    tanggalSiap: '28 September 2026',
    lokasiPengambilan: 'Ruang BKK SMK Sasmita Jaya 2',
    persyaratan: [
      'Membawa KTP / Kartu Pelajar Asli',
      'Mengisi Tracer Study Online',
    ],
    barcode: 'IJZ-SMK-SASMITA-2024-0048293',
  }
};

export const MOCK_ALUMNI_LIST = [
  {
    nama: 'Ahmad Dani',
    jurusan: 'Teknik Komputer dan Jaringan',
    tahunLulus: 2024,
    status: 'KERJA_KULIAH',
    pekerjaan: 'Technical Support di PT Solusi Teknologi Nusantara',
    kampus: 'S1 Teknik Informatika di Universitas Pamulang',
    kota: 'Tangerang Selatan',
    jenisKelamin: 'L',
  },
  {
    nama: 'Siti Nurhaliza',
    jurusan: 'Rekayasa Perangkat Lunak',
    tahunLulus: 2024,
    status: 'KERJA',
    pekerjaan: 'Frontend Developer di PT Kreasi Digital Sinergi',
    kampus: '-',
    kota: 'Jakarta Selatan',
    jenisKelamin: 'P',
  },
  {
    nama: 'Bagas Aditya',
    jurusan: 'Teknik Kendaraan Ringan Otomotif',
    tahunLulus: 2023,
    status: 'WIRAUSAHA',
    pekerjaan: 'Owner Bengkel Modifikasi & Tune Up Bagas Motor',
    kampus: '-',
    kota: 'Depok',
    jenisKelamin: 'L',
  },
  {
    nama: 'Dewi Lestari',
    jurusan: 'Akuntansi & Keuangan Lembaga',
    tahunLulus: 2023,
    status: 'KERJA',
    pekerjaan: 'Tax Consultant Assistant di Kantor Akuntan Publik',
    kampus: '-',
    kota: 'Jakarta Pusat',
    jenisKelamin: 'P',
  },
  {
    nama: 'Fajar Hidayat',
    jurusan: 'Teknik Bisnis Sepeda Motor',
    tahunLulus: 2024,
    status: 'KERJA',
    pekerjaan: 'Senior Mechanic di AHASS Astra Motor Pamulang',
    kampus: '-',
    kota: 'Tangerang Selatan',
    jenisKelamin: 'L',
  },
  {
    nama: 'Maya Anggraini',
    jurusan: 'Bisnis Daring & Pemasaran',
    tahunLulus: 2022,
    status: 'WIRAUSAHA_KULIAH',
    pekerjaan: 'Founder Hijab Fashion Online Store (MayaStore.id)',
    kampus: 'S1 Manajemen Bisnis di Universitas Pamulang',
    kota: 'Tangerang Selatan',
    jenisKelamin: 'P',
  }
];

export const MOCK_FAQS = [
  {
    question: 'Apa itu Tracer Study SMK Sasmita Jaya 2?',
    answer: 'Tracer Study adalah survei penelusuran lulusan yang diselenggarakan untuk merekam rekam jejak alumni setelah lulus (bekerja, kuliah, maupun wirausaha). Hasil survei digunakan untuk akreditasi sekolah dan penyelarasan kurikulum dengan industri.',
  },
  {
    question: 'Apakah data pribadi saya aman dan dirahasiakan?',
    answer: 'Ya, seluruh data alumni dilindungi secara ketat sesuai standar privasi data dan hanya digunakan untuk kepentingan evaluasi pendidikan SMK Sasmita Jaya 2 & pelaporan resmi Kemendikbudristek.',
  },
  {
    question: 'Apakah pengisian Tracer Study menjadi syarat pengambilan ijazah?',
    answer: 'Benar, bukti pengisian kuesioner Tracer Study (QR / Bukti Pengisian Digital) merupakan salah satu kelengkapan berkas saat mengambil ijazah asli di sekolah.',
  },
  {
    question: 'Bagaimana jika saya belum bekerja saat mengisi kuesioner?',
    answer: 'Anda dapat memilih status "Belum Bekerja / Sedang Mencari Kerja". BKK SMK Sasmita Jaya 2 akan membantu memfasilitasi informasi lowongan kerja, pemagangan, dan pelatihan yang sesuai dengan kompetensi Anda.',
  },
  {
    question: 'Bagaimana cara mendaftar lowongan kerja di BKK SMK Sasmita Jaya 2?',
    answer: 'Alumni dapat login ke dashboard, mengakses menu "Info Loker/Magang", dan memilih lowongan yang tersedia untuk melamar langsung atau menghubungi kontak BKK sekolah.',
  },
];
